version: '3.8'

services:
  playwright:
    # Override command for headed mode
    command: npm run test:headed
    # For macOS, use different display setup
    volumes:
      - ./test-results:/app/test-results
      - ./report-db:/app/report-db
      - ./allure-results:/app/allure-results
      - ./env:/app/env
      - ./fixtures:/app/fixtures
      # For macOS, use socat for X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - NODE_ENV=dev
      - CI=false
      - DISPLAY=host.docker.internal:0 