name: Playwright Tests with Allure Report

on:
  push:
    branches: [main, allure-report]
  pull_request:
    branches: [main, allure-report]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  playwright-tests:
    name: "Playwright Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Install Allure CommandLine
        run: |
          curl -o allure-2.22.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.22.1/allure-commandline-2.22.1.tgz
          sudo tar -zxvf allure-2.22.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.22.1/bin/allure /usr/bin/allure
          allure --version

      - name: Run Playwright tests
        env:
          CI: true
        run: |
          npm run allure:clear
          npx playwright test --reporter=allure-playwright

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Store generated Allure report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

  deploy:
    name: "Deploy Allure Report to GitHub Pages"
    needs: playwright-tests
    runs-on: ubuntu-latest
    if: always()

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "allure-report"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
